/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ramadhan Mohammed Mkoma (https://sketchfab.com/ramadhanmkoma9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/angular-brand-480c6c17299f4b6c9a557f2728ad3906
Title: Angular Brand
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function AngularGltf(props) {
  const group = useRef();
  const { nodes } = useGLTF("./assets/models/angular.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="5ce00caaade5466b9b19b5411e5fb704fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="logo"
                  position={[0, 0, 151.109]}
                  rotation={[-Math.PI / 2, 0, 2.904]}
                  scale={190.107}
                >
                  <mesh
                    name="logo_Material001_0"
                    geometry={nodes.logo_Material001_0.geometry}
                  >
                    <meshStandardMaterial color="#e60f2f" />
                  </mesh>
                </group>
                <group
                  name="Camera"
                  position={[-40.863, 187.91, 805.81]}
                  rotation={[0, 1.508, -0.258]}
                  scale={100}
                >
                  <group name="Object_7" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/models/angular.glb");
